//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omu.ProDinner.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dinner
    {
        public int id { get; set; }
        public string name { get; set; }
        public int countryid { get; set; }
        public int chefid { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual chef chef { get; set; }
        public virtual country country { get; set; }
    }
}
